ENSEMBL_VERSION=${ENSEMBL_VERSION:-80}

ENSEMBL_BASE=$HOME/opt/ensembl
ENSEMBL_VBASE=${ENSEMBL_BASE}/${ENSEMBL_VERSION}

PERL5LIB=${ENSEMBL_VBASE}/bioperl-live:${PERL5LIB}
PERL5LIB=${ENSEMBL_VBASE}/ensembl/modules:${PERL5LIB}
PERL5LIB=${ENSEMBL_VBASE}/ensembl-compara/modules:${PERL5LIB}
PERL5LIB=${ENSEMBL_VBASE}/ensembl-variation/modules:${PERL5LIB}
PERL5LIB=${ENSEMBL_VBASE}/ensembl-functgenomics/modules:${PERL5LIB}
export PERL5LIB
