#!/usr/bin/env bash

# Process splign-manual alignments

set -euxo pipefail

source_uta_v=$1
input_dir=$2
working_dir=$3
log_dir=$4

if [ -z "$source_uta_v" ] || [ -z "$input_dir" ] || [ -z "$working_dir" ] || [ -z "$log_dir" ]
then
    echo 'Usage: misc/uta-splign-manual <source_uta_version> <input_dir> <working_dir> <log_dir>'
    exit 1
fi

# set local variables and create working directories
loading_uta_v="uta"
working_dir="$working_dir/splign-manual"
log_dir="$log_dir/splign-manual"
mkdir -p "$log_dir"
mkdir -p "$working_dir"

# Generate txinfo.gz and exonset.gz files
python sbin/generate-loading-data $input_dir/alignments/*.splign --txdata $input_dir/txdata.yaml \
    --output-dir $working_dir 2>&1 | tee "$log_dir/generate-loading-data.log"

# Generate fasta files
seqrepo --root-directory "/biocommons/dl.biocommons.org/seqrepo" \
    export $(gzip -cdq $working_dir/txinfo.gz  | cut -f2 | tail +2) \
    --instance-name "master" | gzip -c > $working_dir/seqs.fa.gz 2>&1 | tee "$log_dir/seqrepo-export.log"

# Generate seqinfo.gz file
sbin/fasta-to-seqinfo -o NCBI $working_dir/seqs.fa.gz | gzip -c > $working_dir/seqinfo.gz 2>&1 | \
    tee "$log_dir/fasta-to-seqinfo.log"

# Load seqinfo
uta --conf=etc/global.conf --conf=etc/uta_dev@localhost.conf load-seqinfo $working_dir/seqinfo.gz 2>&1 | \
    tee "$log_dir/load-seqinfo.log"

# Load txinfo
uta --conf=etc/global.conf --conf=etc/uta_dev@localhost.conf load-txinfo $working_dir/txinfo.gz 2>&1 | \
    tee "$log_dir/load-txinfo.log"

# Load exonset
uta --conf=etc/global.conf --conf=etc/uta_dev@localhost.conf load-exonset $working_dir/exonset.gz 2>&1 | \
    tee "$log_dir/load-exonset.log"

# Align exons
uta --conf=etc/global.conf --conf=etc/uta_dev@localhost.conf align-exons 2>&1 | tee "$log_dir/align-exons.log"

### run diff
sbin/uta-diff "$source_uta_v" "$loading_uta_v" 2>&1 | tee "$log_dir/uta-diff.log"

### psql_dump
pg_dump -U uta_admin -h localhost -d uta -t "$loading_uta_v.gene" | gzip -c > "$working_dir/uta.pgd.gz"
