#!/usr/bin/env python

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

import uta.models

#dsn = 'sqlite:///:memory:'
#dsn = 'sqlite:////tmp/uta.db'
dsn = 'postgresql:///uta'
engine = create_engine(dsn, echo=True)
Session = sessionmaker(bind=engine) 

uta.models.Base.metadata.create_all(engine)

# inject the schema version into the database
session = Session()
session.add(uta.models.Meta(
        key='schema_version', value=uta.models.schema_version))
session.commit()
