#!/usr/bin/env python

import sys, csv

def extract_triplets(hgvslist):
    def first_sw_or_none(hgvslist,sw):
        l = [ x for x in hgvslist if x.startswith(sw) ]
        return l[0] if len(l) > 0 else None

    g = first_sw_or_none(hgvslist,'NC_')
    for tx,pro in [ ('NM_001277115.1','NP_001264044.1'), ('NM_003777.3','NP_003768.2') ]:
        c = first_sw_or_none(hgvslist,tx)
        p = first_sw_or_none(hgvslist,pro)
        yield g,c,p

out = csv.DictWriter(sys.stdout,
                     fieldnames=['rsid','HGVSg','HGVSc','HGVSp'],
                     delimiter='\t')
out.writeheader()

for line in sys.stdin:
    rec = line.strip().split('\t')
    for g,c,p in extract_triplets(rec[6].split(',')):
        if c is None:
            continue
        print('\t'.join(['rs'+rec[0],g,c,p or '']))
