#!/usr/bin/env python

from biomart import BiomartServer

atts = ["external_gene_name", "external_gene_source", "ensembl_gene_id",
        "ensembl_transcript_id", "ensembl_peptide_id"]

server = BiomartServer("http://www.biomart.org/biomart")
hge = server.datasets["hsapiens_gene_ensembl"]

print(server.databases["ensembl"])
s = hge.search({"attributes": atts}, header=1)

for l in s.iter_lines():
    print(l)
