#!/usr/bin/env python
# generate json mapping of seguid => [protein accessions]

import collections
import hashlib
import re
import sys

from Bio import SeqIO
from Bio.SeqUtils.CheckSum import seguid

refseq_ac_re = re.compile(r'ref\|([^|]+)')

print('\t'.join(['seguid','md5','ac']))
for record in SeqIO.parse(sys.stdin, "fasta") :
    seq_seguid = seguid(record.seq.tostring())
    seq_md5 = hashlib.md5(record.seq.tostring()).hexdigest()
    ac = refseq_ac_re.search(record.id).group(1)
    print('\t'.join([seq_seguid,seq_md5,ac]))
