#!/usr/bin/env python

import argparse
import gzip
import logging, logging.config
import os
import pkg_resources
import re
import sys

import Bio.SeqIO
from bdi.utils.aminoacids import seq_md5
import eutils.client

from uta.formats.exonset import ExonSet,ExonSetWriter

def parse_args(argv):
    ap = argparse.ArgumentParser(
        description = __doc__,
        )
    ap.add_argument('GENES',
                    nargs='+')
    ap.add_argument('--with-transcripts','-t',
                    default=False,
                    action='store_true')

    opts = ap.parse_args(argv)
    return opts


if __name__ == '__main__':
    logging_conf_fn = pkg_resources.resource_filename('uta', 'etc/logging.conf')
    logging.config.fileConfig(logging_conf_fn)
    logging.getLogger().setLevel(logging.INFO)
    logger = logging.getLogger(__name__)

    opts = parse_args(sys.argv[1:])

    ec = eutils.client.Client()

    esw = ExonSetWriter(sys.stdout)
    logger.info('Writing exonsets to stdout')

    tx_seen = set()

    for hgnc in opts.GENES:
        e_gene = ec.fetch_gene_by_hgnc(hgnc)
        if e_gene.type != 'protein-coding':
            logger.warning("Skipping {e_gene.hgnc} (not protein coding)".format(e_gene=e_gene))
            continue
        for e_ref in e_gene.references:
            for e_prd in e_ref.products:
                es = ExonSet(tx_ac=e_prd.acv,
                             alt_ac=e_ref.acv,
                             method='splign',
                             strand=e_prd.genomic_coords.strand,
                             exons_se_i=e_prd.genomic_coords.intervals,
                             cds_se_i=None,
                             )
                esw.write(es)

                if opts.with_transcripts and e_prd.acv not in tx_seen:
                    e_tx = ec.fetch_nuccore_by_ac(e_prd.acv)
                    es = ExonSet(tx_ac=e_prd.acv,
                                 alt_ac=e_prd.acv,
                                 method=None,
                                 strand=1,
                                 exons_se_i=e_tx.exons_se,
                                 cds_se_i=e_tx.cds_se,
                                 )
                    esw.write(es)
                    tx_seen.add(e_prd.acv)
