#!/usr/bin/env bash

# This script runs ncbi-download in a docker container.

set -e

DOWNLOAD_DIR=$1

if [ -z "$DOWNLOAD_DIR" ]
then
    echo 'Usage: sbin/ncbi-download-docker <download_dir>'
    exit 1
else
    echo "Downloading files to $DOWNLOAD_DIR"
fi

if [[ $DOWNLOAD_DIR != /* ]]
then
    echo 'Download directory must be an absolute path'
    exit 1
fi

docker build --target uta -t ncbi-download --progress plain .
docker run -it -v $(pwd)/sbin/ncbi-download:/dl-script -v $DOWNLOAD_DIR:/output-dir ncbi-download /dl-script /output-dir
