#!/usr/bin/env bash

set -e

seqrepo_root=$1
seqrepo_version=$2
sequence_dir=$3
log_dir=$4

if [ -z "$seqrepo_root" ] || [ -z "$seqrepo_version" ] || [ -z "$sequence_dir" ] || [ -z "$log_dir" ]
then
    echo 'Usage: sbin/seqrepo-load <seqrepo_root> <seqrepo_version> <sequence_dir> <log_dir>'
    exit 1
fi

# find all fasta files in the working directory
mapfile -t FASTA_FILES < <(find "$sequence_dir" -type f -name "*.f[an]a*")

# Load SeqRepo with new sequences
seqrepo --root-directory "$seqrepo_root" \
    load -n NCBI --instance-name "$seqrepo_version" \
    "${FASTA_FILES[@]}" 2>& 1 | \
    tee "$log_dir/seqrepo-load.log"
