#!/usr/bin/env bash

# This script runs the UTA update procedure.
# It updates the specified UTA and SeqRepo using the given NCBI files.
# It produces a postgres dump of the updated UTA database and an updated SeqRepo (updated in place).
# It expects to be run from the root of the uta repository.

set -e

# export environment variables for docker compose file
export NCBI_DIR=$1
export SEQREPO_DIR=$2
export WORKING_DIR=$3
export UTA_VERSION=$4
export SEQREPO_VERSION=$5

if [ -z "$NCBI_DIR" ] || [ -z "$SEQREPO_DIR" ] || [ -z "$WORKING_DIR" ] || [ -z "$UTA_VERSION" ] || [ -z "$SEQREPO_VERSION" ]
then
    echo 'Usage: sbin/uta-update <ncbi_file_dir> <seqrepo_dir> <working_dir> <uta_version> <seqrepo_version>'
    exit 1
else
    echo "Updating UTA and SeqRepo using files in $NCBI_DIR and SeqRepo data in $SEQREPO_DIR"
    echo "Starting from UTA version $UTA_VERSION and SeqRepo version $SEQREPO_VERSION"
    echo "Logs and intermediate files will be available in $WORKING_DIR"
fi

# Ensure directories are compatible with docker volume usage
if [[ $NCBI_DIR != /* ]] && [[ $NCBI_DIR != .* ]]
then
    echo 'NCBI file directory must start with / or .'
    exit 1
fi

if [[ $SEQREPO_DIR != /* ]] && [[ $SEQREPO_DIR != .* ]]
then
    echo 'SeqRepo data directory must start with / or .'
    exit 1
fi

if [[ $WORKING_DIR != /* ]] && [[ $WORKING_DIR != .* ]]
then
    echo 'Working directory must start with / or .'
    exit 1
fi

# Ensure directories exist.
if [ ! -d "$NCBI_DIR" ]; then
    echo "Directory $NCBI_DIR does not exist."
    exit 1
fi

if [ ! -d "$SEQREPO_DIR" ]; then
    echo "Directory $SEQREPO_DIR does not exist."
    exit 1
fi

if [ ! -d "$WORKING_DIR" ]; then
    echo "Directory $WORKING_DIR does not exist."
    exit 1
fi

# Build the UTA image.
docker build --target uta -t uta-update .

# Bring up a UTA database and run the UTA update procedure.
# docker compose doesn't respect the container name specified in the compose file, so container name is specified here
docker compose run --rm --name uta-update uta-update
