#!/usr/bin/env python

import csv
import fileinput
import logging
import os
import sys

import eutils.client

logging.basicConfig(level=logging.DEBUG)

cols = ['hgnc','tx_ac','pro_ac','origin']

if __name__ == "__main__":
    ec = eutils.client.Client()

    o_flo = csv.DictWriter(f=sys.stdout, fieldnames=cols, delimiter=b'\t')
    o_flo.writeheader()

    for ac in fileinput.input():
        ac = ac.strip()
        esr = ec.esearch(db='nuccore', term=ac)
        assert esr.count == 1, "expected exactly 1 reply for "+ac
        for id in esr.ids:
            gbset = ec.efetch(db='nuccore', id=id)
            assert len(gbset.gbseqs) == 1, "expected exactly 1 reply for id="+id
            gbseq = gbset.gbseqs[0]
            cds_quals = gbseq.features.cds.qualifiers
            o_flo.writerow({
                'hgnc': cds_quals['gene'],
                'tx_ac': gbseq.acv,
                'pro_ac': cds_quals['protein_id'],
                'origin': 'NCBI',
                })
