"""add gene_id to gene and transcript

Revision ID: 595a586e6de7
Revises: a697b584f699
Create Date: 2024-04-10 19:47:43.685672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595a586e6de7'
down_revision: Union[str, None] = 'a697b584f699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('gene_id', sa.Text(), nullable=True), schema='uta')
    op.add_column('gene', sa.Column('type', sa.Text(), nullable=True), schema='uta')
    op.add_column('gene', sa.Column('xrefs', sa.Text(), nullable=True), schema='uta')
    op.add_column('transcript', sa.Column('gene_id', sa.Text(), nullable=True), schema='uta')
    # ### end Alembic commands ###

    # ### commands to drop existing primary key on gene table ###
    op.drop_constraint('gene_pkey', 'gene', schema='uta')
    # ### end of commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'gene_id', schema='uta')
    op.drop_column('gene', 'xrefs', schema='uta')
    op.drop_column('gene', 'type', schema='uta')
    op.drop_column('gene', 'gene_id', schema='uta')
    # ### end Alembic commands ###

    # ### commands to add primary key on gene table ###
    op.create_primary_key('gene_pkey', 'gene', ['hgnc'], schema='uta')
    # ### end of commands ###
