"""hgnc test

Revision ID: 77076df4224c
Revises: 19561fe444c8
Create Date: 2024-08-26 17:08:13.160259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77076df4224c'
down_revision: Union[str, None] = '19561fe444c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_uta_transcript_hgnc'), 'transcript', ['hgnc'], unique=False, schema='uta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uta_transcript_hgnc'), table_name='transcript', schema='uta')
    # ### end Alembic commands ###
