"""add codon_table to Transcript

Revision ID: a697b584f699
Revises: cc51f50ae896
Create Date: 2024-04-08 17:27:41.570024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a697b584f699'
down_revision: Union[str, None] = 'cc51f50ae896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript', sa.Column('codon_table', sa.Integer(), server_default='1', nullable=False), schema='uta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript', 'codon_table', schema='uta')
    # ### end Alembic commands ###
