"""add sqlalchemy model for assocacs

Revision ID: cc51f50ae896
Revises: edadb97f6502
Create Date: 2024-04-05 00:33:40.105587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc51f50ae896'
down_revision: Union[str, None] = 'edadb97f6502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta')
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=False,
               schema='uta')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('associated_accessions', 'pro_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta')
    op.alter_column('associated_accessions', 'tx_ac',
               existing_type=sa.TEXT(),
               nullable=True,
               schema='uta')
    # ### end Alembic commands ###
