# docker compose file for the mito transcript extraction for the UTA update procedure

version: '3'

services:
  mito-extract:
    image: uta-update
    command: sbin/ncbi_process_mito.py NC_012920.1 --output-dir /mito-extract/work | tee /mito-extract/logs/mito.log
    volumes:
      - ${UTA_ETL_WORK_DIR}:/mito-extract/work
      - ${UTA_ETL_LOG_DIR}:/mito-extract/logs
    working_dir: /opt/repos/uta
    network_mode: host
