# https://github.com/actions/stale

name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '1 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          exempt-all-milestones: true
          exempt-draft-pr: true
          exempt-issue-labels: bug,keep-alive
          exempt-pr-labels: bug,keep-alive

          days-before-close: 7
          days-before-stale: 30

          stale-issue-label: stale
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-issue-label: closed-by-stale
          close-issue-message: 'This issue was closed because it has been stalled for 7 days with no activity.'

          stale-pr-label: stale
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 7 days.'
          close-pr-label: closed-by-stale
          close-pr-message: 'This PR was closed because it has been stalled for 7 days with no activity.'
