name: UTA Update

on:
  workflow_dispatch:
    inputs:
      run-uta-update:
        description: Run UTA update
        type: boolean
        default: true

env:
  UTA_V: 20210129b

jobs:
  summarize-inputs:
    name: Workflow inputs
    runs-on: ubuntu-latest
    steps:
      - name: Dump GHA inputs to summary page
        uses: actions/github-script@v6
        env:
          INPUTS_JSON: ${{ toJson(inputs) }}
        with:
          script: |
            await core.summary
            .addHeading('Inputs')
            .addCodeBlock(JSON.stringify(JSON.parse(process.env.INPUTS_JSON), null, 2), 'json')
            .write()
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change dir
        run: cd loading
      - name: Build the stack
        env:
            uta_v: ${{ env.UTA_V }
        run: docker-compose up -d
      - name: Bring up the stack
        env:
            uta_v: ${{ env.UTA_V }
        run: docker-compose up
      - name: Bring down the stack
        env:
            uta_v: ${{ env.UTA_V }
        run: docker-compose down --volumes

