name: UTA Update

on:
  workflow_dispatch:
    inputs:
      run-uta-update:
        description: Run UTA update
        type: boolean
        default: true


jobs:
  summarize-inputs:
    name: Workflow inputs
    runs-on: ubuntu-latest
    steps:
      - name: Dump GHA inputs to summary page
        uses: actions/github-script@v6
        env:
          INPUTS_JSON: ${{ toJson(inputs) }}
        with:
          script: |
            await core.summary
            .addHeading('Inputs')
            .addCodeBlock(JSON.stringify(JSON.parse(process.env.INPUTS_JSON), null, 2), 'json')
            .write()
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker
        uses: docker/setup-action@v2
        with:
          docker-version: '20.10.7'
      - name: Build Docker Compose Services
        uses: docker/compose-action@v2
        with:
          file: loading/docker-compose.yml
          services: uta_python
          build: --build
      - name: Start Docker Compose Services
        uses: docker/compose-action@v2
        with:
          file: loading/docker-compose.yml
          services: uta_python
      - name: Execute Commands Inside Container
        uses: docker/exec-action@v2
        with:
          container: some_stuff_python
          run: PGPASSWORD=anonymous psql -h postgres -U anonymous -d uta
        env:
          DOCKER_CLI: bash
        timeout-minutes: 5

